name = "bitebase-backend"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "bitebase-backend-production"
route = "https://api.bitebase.com/*"

[env.staging]
name = "bitebase-backend-staging"
route = "https://api-staging.bitebase.com/*"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-id"

# D1 Database (Cloudflare's SQLite)
[[d1_databases]]
binding = "DB"
database_name = "bitebase-db"
database_id = "your-d1-database-id"

# R2 Storage for files
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "bitebase-storage"

# Environment variables
[vars]
NODE_ENV = "production"
GOOGLE_MAPS_API_KEY = "AIzaSyCfG9E3ggBc1ZBkhqTEDSBm0eYp152tMLk"

# Secrets (set these via wrangler secret)
# wrangler secret put DATABASE_URL
# wrangler secret put REDIS_URL
# wrangler secret put JWT_SECRET
# wrangler secret put AWS_ACCESS_KEY_ID
# wrangler secret put AWS_SECRET_ACCESS_KEY